name: Run tests and coverage backend

on:
  push:
    branches:
      - develop
    paths:
      - 'back/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'back/**'
      - '.github/workflows/backend-tests.yml'


jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven tests
        run:
          mvn clean
          mvn test jacoco:report

      - name: Upload backend test results
        uses: actions/upload-artifact@v3
        with:
          name: backend-test-results
          path: back/target/site/jacoco